version: "3.7"
services:

  my-envoy:
    build:
      context: .
      dockerfile: Dockerfile
    # command: -l debug --config-path /etc/envoy/envoy.yaml
    expose:
      - "10001"
    ports:
      - "10001:10001"

  nodeserv:
    build:
      context: .
      dockerfile: Dockerfile.nodeserver
    expose:
      - "8081"
    ports:
      - "8081:8081"
